FROM timescale/timescaledb:0.9.2-pg10

ARG GO_PASSWORD=123456
ENV GO_PASSWORD=${GO_PASSWORD}
ARG WEB_PASSWORD=123456
ENV WEB_PASSWORD=${WEB_PASSWORD}

RUN mkdir -p /tmp/conf

COPY ./db/conf /tmp/conf
COPY ./db/init.db.sh /docker-entrypoint-initdb.d