FROM timescale/timescaledb:0.9.2-pg10

ARG TURTLECOINSERVICE_PASSWORD=98765
ENV TURTLECOINSERVICE_PASSWORD=${TURTLECOINSERVICE_PASSWORD}
ARG WEB_PASSWORD=98765
ENV WEB_PASSWORD=${WEB_PASSWORD}

RUN mkdir -p /tmp/conf

COPY ./db/daemon/conf /tmp/conf
COPY ./db/daemon/init.db.sh /docker-entrypoint-initdb.d