# daemon runs in the background
# run something like tail /var/log/turtlecoind/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/turtlecoind:/var/lib/turtlecoind -v $(pwd)/wallet:/home/turtlecoin --rm -ti turtlecoin:0.2.2
ARG base_image_version=0.10.0
FROM phusion/baseimage:$base_image_version

ARG TURTLECOIN_BRANCH=master
ENV TURTLECOIN_BRANCH=${TURTLECOIN_BRANCH}

ARG TURTLECOIN_PROGRAM=TurtleCoind
ENV TURTLECOIN_PROGRAM=${TURTLECOIN_PROGRAM}

# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev \
      librocksdb-dev \
      libreadline-dev && \
    mkdir -p /src/turtlecoin

WORKDIR /src/turtlecoin

RUN git clone -b $TURTLECOIN_BRANCH --single-branch https://github.com/turtlecoin/turtlecoin.git . && \
    mkdir build

WORKDIR /src/turtlecoin/build

RUN cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) $TURTLECOIN_PROGRAM

RUN mkdir -p /usr/local/bin && \
    cp src/$TURTLECOIN_PROGRAM /usr/local/bin/$TURTLECOIN_PROGRAM && \
    strip /usr/local/bin/$TURTLECOIN_PROGRAM

WORKDIR /

RUN rm -rf /src/turtlecoin && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev librocksdb-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55